### ISSUE TITLE
Melhorar o global.css com a page.tsx

### ISSUE THREAD

**Issue by Dolfino** [Dolfino/somapay#7]
Para melhorar o globals.css com base nos padrões, componentes e estilos recorrentes usados em page.tsx, seguem sugestões práticas para tornar o CSS mais consistente, reutilizável e alinhado ao design do projeto. Veja exemplos de melhorias e adições:

````css
/*...existing code...*/

/* === COMPONENTES E UTILITÁRIOS INSPIRADOS EM page.tsx === */

/* Cards customizados */
.card {
  @apply bg-white rounded-2xl shadow-lg border border-gray-100 transition-all duration-300;
}
.card-hover {
  @apply hover:shadow-2xl hover:-translate-y-2;
}

/* Botões principais */
.btn {
  @apply inline-flex items-center justify-center rounded-lg font-semibold transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2;
}
.btn-primary {
  @apply bg-primary-600 text-white hover:bg-primary-700 focus:ring-primary-500;
}
.btn-secondary {
  @apply bg-secondary-600 text-white hover:bg-secondary-700 focus:ring-secondary-500;
}
.btn-outline-secondary {
  @apply border border-secondary-600 text-secondary-600 hover:bg-secondary-600 hover:text-white;
}
.btn-lg {
  @apply px-8 py-4 text-lg;
}

/* Inputs e formulários */
.input {
  @apply w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors;
}
.input-error {
  @apply border-red-300 focus:ring-red-500;
}

/* Checkbox e radio customizados */
.input-radio,
.input-checkbox {
  @apply h-4 w-4 text-primary-600 border-gray-300 focus:ring-primary-500;
}

/* Gradientes usados em seções */
.bg-hero-gradient {
  background: linear-gradient(135deg, #6a7bff 0%, #8b5cf6 60%, #f1701e 100%);
}
.bg-section-light {
  @apply bg-gray-50;
}
.bg-section-dark {
  @apply bg-gradient-to-br from-primary-900 via-primary-800 to-accent-900 text-white;
}

/* Utilitário para overlays */
.overlay {
  @apply absolute inset-0 bg-black/40;
}

/* Utilitário para imagens responsivas */
.img-responsive {
  @apply w-full h-auto object-cover;
}

/* Utilitário para títulos de seção */
.section-title {
  @apply text-3xl md:text-5xl font-bold text-gray-900 mb-6;
}

/* Utilitário para subtítulos */
.section-subtitle {
  @apply text-xl text-gray-600 max-w-3xl mx-auto;
}

/* Utilitário para animação de loading */
.loading {
  @apply opacity-50 pointer-events-none;
}
.spinner {
  @apply animate-spin rounded-full border-2 border-gray-300 border-t-primary-600;
}

/* Utilitário para botões de ação */
.action-link {
  @apply text-primary-600 hover:text-primary-700 font-semibold flex items-center gap-2;
}

/* Utilitário para listas de rodapé */
.footer-list {
  @apply space-y-2 text-gray-300;
}
.footer-title {
  @apply text-lg font-semibold mb-4;
}

/* Utilitário para ícones sociais */
.social-icon {
  @apply flex items-center justify-center w-10 h-10 rounded-full border-2 border-white transition-colors;
  background: rgba(255,255,255,0.08);
}

/* Utilitário para badge/selo */
.badge {
  @apply inline-block px-3 py-1 rounded-full text-xs font-semibold;
}

/* Utilitário para grid responsivo de produtos/blog */
.grid-auto {
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
}

/* Utilitário para gradiente de texto */
.text-gradient {
  @apply bg-gradient-to-r from-primary-600 to-accent-600 bg-clip-text text-transparent;
}

/*...existing code...*/
````

**Como usar:**
- Substitua classes repetidas em page.tsx por utilitários como `.btn`, `.card`, `.input`, `.section-title`, `.footer-list`, etc.
- Use `.bg-hero-gradient` para backgrounds de seções principais.
- Use `.social-icon` para links de redes sociais.
- Use `.action-link` para botões de "Ler mais" ou "Saiba mais".

Essas melhorias deixam o CSS mais limpo, DRY e fácil de manter, além de facilitar a padronização visual em todo o projeto.
